# Documentation
# https://github.com/elastic/helm-charts/tree/master/elasticsearch
elasticsearch:
  # only needed for local installations with only one node available
  # elastic setup consists of 2 default instances with antiAffinity configured to support failover
  antiAffinity: "soft"
  replicas: 2
  minimumMasterNodes: 1


# Documentation
# https://github.com/elastic/helm-charts/tree/master/kibana
#kibana:


# Documentation
# https://github.com/fluent/helm-charts/tree/main/charts/fluentd:
fluentd:
  dashboards:
    enabled: false

  fileConfigs:
    02_filters.conf: |-
      <label @KUBERNETES>
        <match kubernetes.var.log.containers.fluentd**>
          @type relabel
          @label @FLUENT_LOG
        </match>

        # <match kubernetes.var.log.containers.**_kube-system_**>
        #   @type null
        #   @id ignore_kube_system_logs
        # </match>

        <filter kubernetes.**>
          @type kubernetes_metadata
          @id filter_kube_metadata
          skip_labels false
          skip_container_metadata false
          skip_namespace_metadata true
          skip_master_url true
        </filter>

        <filter kubernetes.var.log.containers.**>
          @type parser
          <parse>
            @type json
            json_parser json
          </parse>
          replace_invalid_sequence true
          emit_invalid_record_to_error false
          key_name log
          reserve_data true
        </filter>

        <match **>
          @type relabel
          @label @DISPATCH
        </match>
      </label>
